import Navbar from "../../components/Navbar";
import Topheader from "../../components/Topheader";
import "./globals.css";
import styles from "./page.module.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body>
          <div className={styles.home_container}>
            <Topheader />
            <Navbar />
            {children}
          </div>
        </body>
      </html>
  );
}
