"use client"
import Navbar from "../../components/Navbar";
import Topheader from "../../components/Topheader";
import Footer from "../../components/Footer";
import Hottopic from "../../components/Hottopic";
import { useRouter } from 'next/navigation';
import "./globals.css";
import styles from "./page.module.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const noNav = ['/dashboard'];

export default function RootLayout({ children }) {
  const router = useRouter();
  const { asPath } = router;
  const excludeNavAndFooter = noNav.includes(asPath);


  return (
    <html lang="en">
      <body>
          <div className={styles.home_container}>
            <Topheader />
            {!excludeNavAndFooter && <Navbar />}
            <Hottopic />
            {children}
            <Footer />
          </div>
      </body>
    </html>
  );
}
// import { useRouter } from 'next/router';
// function Myapp({Component, pageProps}){
// const router = useRouter();
// const { asPath } = router;
// const noNav =  ['/login', '/Registration'];
// return(
//        {noNav.includes(asPath) ? null : <Nav />}
//           <Component {...pageProps} />
//          {noNav.includes(asPath) ? null : <Footer />}
// );
// }