import Navbar from "../../components/Navbar";
import Topheader from "../../components/Topheader";
import Footer from "../../components/Footer";

import "./globals.css";
import styles from "./page.module.css";
import SideMenu from "../../components/SideMenu";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body>
          <div className={styles.home_container}>
            {/* <SideMenu/> */}
            <Topheader />
            <Navbar />
            {children}
            <Footer/>
          </div>
        </body>
      </html>
  );
}
